<?xml version="1.0" encoding="utf-8"?><Database Name="Webstore" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Webstore.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebstoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="category_product" Member="products" ThisKey="Id" OtherKey="categoryID" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.city" Member="cities">
    <Type Name="city">
      <Column Name="zipcode" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="city_customer" Member="customers" ThisKey="zipcode" OtherKey="zipcode" Type="customer" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="customerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="order_orderdetail" Member="orderdetails" ThisKey="Id" OtherKey="orderID" Type="orderdetail" />
      <Association Name="customer_order" Member="customer" ThisKey="customerID" OtherKey="Id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orderdetail" Member="orderdetails">
    <Type Name="orderdetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="order_orderdetail" Member="order" ThisKey="orderID" OtherKey="Id" Type="order" IsForeignKey="true" />
      <Association Name="product_orderdetail" Member="product" ThisKey="productID" OtherKey="Id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="categoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="product_orderdetail" Member="orderdetails" ThisKey="Id" OtherKey="productID" Type="orderdetail" />
      <Association Name="category_product" Member="category" ThisKey="categoryID" OtherKey="Id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="zipcode" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.Data.Linq.Binary" DbType="VarBinary(256) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="customer_order" Member="orders" ThisKey="Id" OtherKey="customerID" Type="order" />
      <Association Name="city_customer" Member="city" ThisKey="zipcode" OtherKey="zipcode" Type="city" IsForeignKey="true" />
    </Type>
  </Table>
</Database>